package com.brands.dao;
// Generated Apr 15, 2020, 2:02:32 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="cart"
    ,catalog="brands"
)
public class Cart implements java.io.Serializable {


    private Integer cartId;
    private Date buyingDate;
    private Set<Users> userses = new HashSet<Users>(0);
    private Set<Products> productses = new HashSet<Products>(0);

    public Cart() {
    }

    public Cart(Set<Users> userses, Set<Products> productses) {
        this.userses = userses;
        this.productses = productses;
    }

    public Cart(Date buyingDate, Set<Users> userses, Set<Products> productses) {
        this.buyingDate = buyingDate;
        this.userses = userses;
        this.productses = productses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "cart_id", unique = true, nullable = false)
    public Integer getCartId() {
        return this.cartId;
    }

    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="buying_date", length=19)
    public Date getBuyingDate() {
        return this.buyingDate;
    }
    
    public void setBuyingDate(Date buyingDate) {
        this.buyingDate = buyingDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
    public Set<Products> getProductses() {
        return this.productses;
    }

    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }


}


