package com.brands.dao;
// Generated Apr 9, 2020, 8:56:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="brands"
)
public class Products  implements java.io.Serializable {


     private Integer productId;
     private Category category;
     private String name;
     private int quantity;
     private double price;
     private String describtion;
     private Set<Users> userses = new HashSet<Users>(0);

    public Products() {
    }

	
    public Products(int quantity, double price) {
        this.quantity = quantity;
        this.price = price;
    }
    public Products(Category category, String name, int quantity, double price, String describtion, Set<Users> userses) {
       this.category = category;
       this.name = name;
       this.quantity = quantity;
       this.price = price;
       this.describtion = describtion;
       this.userses = userses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="describtion", length=80)
    public String getDescribtion() {
        return this.describtion;
    }
    
    public void setDescribtion(String describtion) {
        this.describtion = describtion;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="productses")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


