package com.brands.dao;
// Generated Apr 15, 2020, 2:02:32 AM by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products"
        , catalog = "brands"
)
public class Products implements java.io.Serializable {


    private int productId;
    private Cart cart;
    private Category category;
    private Users users;
    private String name;
    private int quantity;
    private double price;
    private String describtion;
    private byte[] image;

    public Products() {
    }


    public Products(int productId, Cart cart, Users users, int quantity, double price) {
        this.productId = productId;
        this.cart = cart;
        this.users = users;
        this.quantity = quantity;
        this.price = price;
    }

    public Products(int productId, Cart cart, Category category, Users users, String name, int quantity, double price, String describtion, byte[] image) {
        this.productId = productId;
        this.cart = cart;
        this.category = category;
        this.users = users;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
        this.describtion = describtion;
        this.image = image;
    }

    @Id


    @Column(name = "product_id", unique = true, nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cart_id", nullable = false)
    public Cart getCart() {
        return this.cart;
    }

    public void setCart(Cart cart) {
        this.cart = cart;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="describtion", length=80)
    public String getDescribtion() {
        return this.describtion;
    }
    
    public void setDescribtion(String describtion) {
        this.describtion = describtion;
    }

    
    @Column(name="image")
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


